# Generated by Django 2.0.5 on 2018-05-21 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCategoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=45)),
                ('emailCliente', models.CharField(max_length=100)),
                ('telefoneCliente', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('idDrone', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'Disponivel'), ('2', 'Indisponivel'), ('3', 'em manutenção')], max_length=45)),
                ('capacidadeCarga', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idEndereco', models.AutoField(primary_key=True, serialize=False)),
                ('quadra', models.CharField(max_length=45)),
                ('alameda', models.CharField(max_length=45)),
                ('lote', models.CharField(max_length=45)),
                ('complemento', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('idFormaPagamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPagamento', models.CharField(choices=[('1', 'credito'), ('2', 'debito')], max_length=45)),
                ('parcelas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdItens', models.IntegerField()),
                ('valorTotal', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('idMercado', models.AutoField(primary_key=True, serialize=False)),
                ('nomeMercado', models.CharField(max_length=45)),
                ('emailMercado', models.CharField(max_length=100)),
                ('telefoneMercado', models.CharField(max_length=45)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Mercado_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Mercado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('dataPedido', models.DateTimeField(default=datetime.datetime(2018, 5, 21, 15, 39, 28, 265363))),
                ('valorPedido', models.FloatField()),
                ('qtdProdutos', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Cliente')),
                ('enderecoEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nomeProduto', models.CharField(max_length=45)),
                ('precoProduto', models.FloatField(max_length=100)),
                ('qtdProduto', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('idTracking', models.AutoField(primary_key=True, serialize=False)),
                ('localizacao', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Drone')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='bd.Produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Tracking'),
        ),
        migrations.AddField(
            model_name='mercado_produto',
            name='produto',
            field=models.ManyToManyField(to='bd.Produto'),
        ),
        migrations.AddField(
            model_name='itenspedidos',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Pedido'),
        ),
    ]
