# Generated by Django 2.1a1 on 2018-05-23 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('indisponivel', 'Indisponivel'), ('manutencao', 'em manutenção')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 17, 37, 47, 447105)),
        ),
    ]
